name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    permissions: # <- this section is needed for workload identity
      contents: 'read'
      id-token: 'write'
    env:
      IMAGE_NAME: g4s-bids-api-ui
      REPO_NAME: github-bids
      PROJECT_ID: g4s-skunkworks
      SERVICE_ACCOUNT: 'bid-generation@g4s-skunkworks.iam.gserviceaccount.com'
    steps:
    - uses: actions/checkout@v3
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/879087998271/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-provider'
        service_account: 'bid-generation@g4s-skunkworks.iam.gserviceaccount.com'

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest europe-west2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest europe-west2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GIT_TAG
        docker push europe-west2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
        docker push europe-west2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GIT_TAG
